version: "3"
services:
  springBootApp:
    image: sathyamurthyr/user-service:1.0
    container_name: docker-postgres-springboot-demo-app
    environment:
      - POSTGRES_HOST=docker-postgres-springboot-demo-db
    ports:
      - "8081:8096"
    networks:
      - network
    depends_on:
      - postgresDB
    restart: on-failure
  postgresDB:
    image: postgres:13.2
    container_name: docker-postgres-springboot-demo-db
    ports:
      - "5434:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sapient@12345
      - POSTGRES_DB=testdb
networks:
  network:
volumes:
  volume: 